server:
  port: 8081

spring:
  application:
    name: UserApp

  datasource:
    url: jdbc:mysql://root@localhost:3306/microservice
    username: root
    password: Avyaan@123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka